language: php

php:
  - '7.4'
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit Tests --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
